name: Publish

on:
  release:
    types: [published]

jobs:
  # Job to publish to npm registry
  npm-publish:
    name: Publish to npm
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js for npm registry
      - name: Setup Node.js for npm
        uses: actions/setup-node@v4
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"
          scope: "@manojtharindu11"

      # Step 3: Authenticate npm for publishing to npm registry
      - name: Authenticate npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc

      # Step 4: Publish to npm registry
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  # Job to publish to GitHub Packages
  github-publish:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    needs: npm-publish  # Ensure this job runs after npm-publish job completes

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js for GitHub Packages
      - name: Setup Node.js for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: "14"
          registry-url: "https://npm.pkg.github.com"
          scope: "@manojtharindu11"

      # Step 3: Authenticate for GitHub Packages
      - name: Authenticate GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PAT }}" >> ~/.npmrc

      # Step 4: Publish to GitHub Packages
      - name: Publish to GitHub Packages
        run: npm publish --registry https://npm.pkg.github.com --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PAT }}
